import { useNavigate } from 'react-router-dom';

const AIAnalysisReport = () => {
  const navigate = useNavigate();

  const handleProceed = () => {
    navigate('/login');
  };

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col items-center justify-center p-6">
      <div className="w-full max-w-4xl bg-white rounded-xl shadow-lg overflow-hidden p-8">
        {/* Header Section */}
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold text-gray-800 mb-2">AI Analysis Report</h1>
          <p className="text-gray-600">Detailed insights generated by our AI system</p>
        </div>

        {/* Blank Content Area - Can be populated with actual analysis later */}
        <div className="border-2 border-dashed border-gray-300 rounded-lg p-8 mb-8 min-h-64 flex items-center justify-center">
          <p className="text-gray-500 text-center">
            AI-generated analysis content will appear here
          </p>
        </div>

        {/* Proceed Button */}
        <div className="flex justify-end">
          <button
            onClick={handleProceed}
            className="w-full py-3 px-4 bg-green-600 hover:bg-green-700 text-white font-medium rounded-lg transition-colors focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2"
          >
            Proceed
          </button>
        </div>
      </div>
    </div>
  );
};

export default AIAnalysisReport;